# /.github/workflows/test-0cherry-github-action.yml
name: Github Action Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-github-action:
    runs-on: ubuntu-latest

    steps:
      - name: "add actions test"
        uses: 0cherry/0cherry-github-action@master
        id: test