# /.github/workflows/test-0cherry-github-action.yml
name: Github Action Test

on:
  push:
    branches: [ master ]
#  pull_request:
#    branches: [ master ]
#  schedule:
#    - cron: "30 * * * 1-5"

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Do my action & create report file
        uses: 0cherry/0cherry-github-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: ${{ github.ref }}
      